// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpalmxpgdffvqjlcmfcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYWxteHBnZGZmdnFqbGNtZmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODEzNjgsImV4cCI6MjA1OTY1NzM2OH0.9AuNToiPVz5wob3M26wtnkiufV3j4FTuLpGTEFOoZK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);